'''A rough file for testing the functions of the package.'''

from core import _handle_multihead
from core import _restore_multihead
import torch as th
from core import _safe_norm
from core import _householder_rotation
from core import _adaptive_scale
from core import RotationQuantization
from core import attach_rotator
print("\n=== Testing multi-head handling and restoration ===\n")
A = th.tensor([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
flattened, shape_info = _handle_multihead(A)
restored = _restore_multihead(flattened, shape_info)
print("Original Tensor:")
print(A.shape)
print("Flattened Tensor:")
print(flattened.shape)
print("Restored Tensor:")
print(restored.shape)
print("\nShape Info:")
print(shape_info)
B = th.randn(2, 3, 4)
flattened_B, shape_info_B = _handle_multihead(B)
print("\nTensor B:")
print(B.shape)
print("Flattened Tensor B:")
print(flattened_B.shape)
print("Restored Tensor B:")
restored_B = _restore_multihead(flattened_B, shape_info_B)
print(restored_B.shape)
print("\nShape Info B:")
print(shape_info_B)
print("\n=== Testing _safe_norm ===\n")
v = th.tensor([3.0, 4.0])
norm = _safe_norm(v)
print(f"v: {v}")
print(f"norm: {norm.item()}")  
z = th.zeros(5)
norm = _safe_norm(z)
print(f"\nZero vector norm: {norm.item()}")
batch = th.tensor([[1.0, 2.0], [3.0, 4.0], [0.0, 0.0]])
norms = _safe_norm(batch, dim=-1)
print(f"\nBatch norms: {norms.squeeze(-1)}")
th.manual_seed(42)
e = th.randn(4, 8)
q = th.randn(4, 8)
grad = th.randn(4, 8)
rotated = _householder_rotation(e, q, grad)
print("Rotation norm preservation:", th.allclose(rotated.norm(dim=-1), grad.norm(dim=-1), atol=1e-5))
e_zero = th.zeros(4, 8)
q_zero = th.zeros(4, 8)
grad_zero = th.randn(4, 8)
rotated_zero = _householder_rotation(e_zero, q_zero, grad_zero)
print("Zero fallback works:", th.allclose(rotated_zero, grad_zero))
print("\n=== Testing _adaptive_scale ===\n")
th.manual_seed(42)
e = th.randn(4, 8)
q = th.randn(4, 8)
grad = th.randn(4, 8)
dim = 8
scaled = _adaptive_scale(e, q, grad, dim)
print(f"e shape: {e.shape}")
print(f"q shape: {q.shape}")
print(f"grad shape: {grad.shape}")
print(f"scaled shape: {scaled.shape}")
scale_factors = (scaled / grad).abs()
print(f"Min scale factor: {scale_factors.min().item():.4f}")
print(f"Max scale factor: {scale_factors.max().item():.4f}")
print(f"All within [0.1, 10.0]? {(scale_factors.min() >= 0.1 and scale_factors.max() <= 10.0)}")
e_zero = th.zeros(4, 8)
q_zero = th.zeros(4, 8)
grad_zero = th.randn(4, 8)
scaled_zero = _adaptive_scale(e_zero, q_zero, grad_zero, dim)
scale_zero = (scaled_zero / grad_zero).abs()
print(f"\nZero vector scale: {scale_zero.mean().item():.4f} (should be ~0.1)")
print("\n=== Testing RotationQuantization ===\n")
th.manual_seed(42)
e = th.randn(4, 8, requires_grad=True)
q = th.randn(4, 8)
for strategy in ["ste", "rotation", "adaptive"]:
    print(f"Testing: {strategy}")
    q_out = RotationQuantization.apply(e, q, strategy, 1.0, True, 1e-8)
    loss = (q_out ** 2).sum()
    loss.backward(retain_graph=True)
    print(f"  Gradient norm: {e.grad.norm().item():.6f}")
    e.grad.zero_()

class DummyQuantizer(th.nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = th.nn.Embedding(512, 8)
    def forward(self, z):
        z_flat = z.view(-1, z.shape[-1])
        distances = th.cdist(z_flat, self.embedding.weight)
        indices = th.argmin(distances, dim=1)
        z_q = self.embedding(indices).view(z.shape)
        return z_q
vq = DummyQuantizer()
attach_rotator(vq, strategy="adaptive")

z = th.randn(4, 8, requires_grad=True)
z_q = vq(z)

print(f"Input: {z.shape}, Output: {z_q.shape}")
print("Gradient test...")
loss = (z_q ** 2).sum()
loss.backward()
print(f"Gradient norm: {z.grad.norm().item():.6f}")
print(" System ready!")